name: kennemer
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: kennemer:prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: "80"
      HOST: "0.0.0.0"
      HTTPS_PORT: "443" # optional: remove or change if you don't need TLS
      # HTTPS_KEY_PATH: /certs/server.key
      # HTTPS_CERT_PATH: /certs/server.crt
      # HTTPS_CA_PATH: /certs/ca.pem
      # HTTPS_PASSPHRASE: example-passphrase
    ports:
      - "80:80"
      - "443:443"
    working_dir: /app
    env_file:
      - ./app/.env
    # volumes:
    #   - ./certs/server.key:/certs/server.key:ro
    #   - ./certs/server.crt:/certs/server.crt:ro
    #   - ./certs/ca.pem:/certs/ca.pem:ro
